triggers:
- description: null
  envs: []
  last_enabled_at: 2026-02-16 00:45:22.739721
  name: illuminated butterfly
  pipeline_uuid: gold_layer_state
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2026-02-16 00:41:00
  status: active
  token: 812879650d634b63a7840e26714ac7f4
  variables: {}
